name: Release Build
on:
  push:
    tags:
      - 'v*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Force fetch annotated tags (workaround)
        # Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --force --tags
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: build-artifacts-*
        merge-multiple: true
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "*.zip"

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Force fetch annotated tags (workaround)
        # Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --force --tags
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Install ANTLR
      run: pip install antlr4-tools
    - name: Build and Test
      run: make
    - name: Zip Artifact
      run: powershell Compress-Archive scadformat.exe windows.zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-windows
        path: windows.zip

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Force fetch annotated tags (workaround)
        # Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --force --tags
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Install ANTLR
      run: pip install antlr4-tools
    - name: Build and Test
      run: make
    - name: Zip Artifact
      run: zip macos.zip scadformat
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-macos
        path: macos.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Force fetch annotated tags (workaround)
        # Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --force --tags
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Install ANTLR
      run: pip install antlr4-tools
    - name: Build and Test
      run: make
    - name: Zip Artifact
      run: zip linux.zip scadformat
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-linux
        path: linux.zip
